# https://scrutinizer-ci.com/g/newcontext-oss/kitchen-terraform/
---
build:
  environment:
    postgresql: false
    redis: false
    ruby: '2.3.1'
    variables:
      SCRUTINIZER_REPOSITORY: newcontext-oss/kitchen-terraform

checks:
  ruby: true

tools:
  rubocop:
    use_native_config: true
